name: Install GeoGate 
author: Ufuk Turuncoglu
description: 'Install GeoGate co-processing component'
inputs:
  compiler:
    description: 'Compiler type and version'
    required: true 
    type: string
  install_dir:
    description: 'Installation directory'
    required: true
    type: string
  spack_dir:
    description: 'Directory of Spack installation'
    required: true 
    type: string
  use_python:
    description: 'Activate Python support'
    required: false
    type: string
    default: ON
  use_catalyst:
    description: 'Activate ParaView Catalyst support'
    required: false
    type: string
    default: ON

runs:
  using: composite
  steps:
  - name: Install GeoGate 
    run: |
      cd ${{ inputs.install_dir }}
      . ${{ inputs.spack_dir }}/share/spack/setup-env.sh
      . $(spack location -i lmod)/lmod/lmod/init/bash
      spack env activate test
      module load esmf
      module load libcatalyst
      module load conduit
      export COMPILER_MAJOR_VER=`echo ${{ inputs.compiler }} | awk -F@ '{print $2}' | awk -F. '{print $1}'`
      export FC=/usr/bin/gfortran-$COMPILER_MAJOR_VER
      export CC=/usr/bin/gcc-$COMPILER_MAJOR_VER
      export CXX=/usr/bin/g++-$COMPILER_MAJOR_VER
      cd geogate
      mkdir build
      cd build
      cmake -DCMAKE_INSTALL_PREFIX=${{ inputs.install_dir }}/geogate/install \
         -DGEOGATE_USE_PYTHON=${{ inputs.use_python }} \
         -DGEOGATE_USE_CATALYST=${{ inputs.use_catalyst }} \
         -DCMAKE_BUILD_TYPE=Debug
         -DCMAKE_Fortran_FLAGS="-ffree-form -ffree-line-length-none" \
         ../src/
      make VERBOSE=1
      make install
    shell: bash
