ESMX:
  App: 
    globalResourceControl: true
    logKindFlag: ESMF_LOGKIND_Multi
    logAppendFlag: false
    logFlush: true
    fieldDictionary: fd_ufs.yaml
    startTime: 2024-08-11T12:00:00
    stopTime: 2024-08-14T12:00:00
  Driver:
    componentList: [ATM, OCN, COP]
    attributes:
      Verbosity: low
    runSequence: |
      @43200
        ATM -> COP :remapMethod=redist
        OCN -> COP :remapMethod=redist
        COP geogate_phases_catalyst
        #COP geogate_phases_io
        #COP geogate_phases_python
        ATM
        OCN
      @
generalAttributes: &anchor
  case_name: cop_test
  stop_n: 3
  stop_option: ndays
  stop_ymd: -999
  restart_n: 1
  restart_option: never
  restart_ymd: -999
ATM:
  model: datm
  petList: 0-1
  attributes: 
    Verbosity: low 
    Diagnostic: 0
    read_restart: .false.
    orb_eccen: 1.e36
    orb_iyear: 2000
    orb_iyear_align: 2000
    orb_mode: fixed_year
    orb_mvelp: 1.e36
    orb_obliq: 1.e36
    ScalarFieldCount: 3
    ScalarFieldIdxGridNX: 1
    ScalarFieldIdxGridNY: 2
    ScalarFieldIdxNextSwCday: 3
    ScalarFieldName: cpl_scalars
    <<: *anchor
OCN:
  model: docn
  petList: 0-1
  attributes:
    Verbosity: low
    Diagnostic: 0
    read_restart: .false.
    ScalarFieldCount: 3
    ScalarFieldIdxGridNX: 1
    ScalarFieldIdxGridNY: 2
    ScalarFieldIdxNextSwCday: 3
    ScalarFieldName: cpl_scalars
    <<: *anchor
COP:
  model: geogate
  petList: 2-5
  attributes: 
    Verbosity: low 
    Diagnostic: 0
    KeepFieldList: Sa_u10m:Sa_v10m:So_t
    CatalystConvertToCart: .true.
    CatalystScripts: catalyst_grid_writer.py
    CatalystLoadPath: __CATALYST_LOAD_PATH__
    <<: *anchor
