name: Test plugins

env:
  spack_version: v1.0.0-alpha.2

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  types: [opened, synchronize, reopened, labeled, unlabeled]
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-24.04
    steps:
    # Prepare core environment
    - name: Install Core Development Tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install tar unzip file curl gringo
        sudo apt-get -qq install build-essential binutils-dev gfortran gdb
        sudo apt-get -qq install python3-dev

    # Concretize Spack test environment 
    - name: Concretize Spack Environment Using YAML Specification
      run: |
        cd ${{ github.workspace }}
        echo "::group:: Setup Spack"
        git clone -b ${{ env.spack_version }} https://github.com/spack/spack.git
        . spack/share/spack/setup-env.sh
        spack compiler find
        cat ~/.spack/linux/compilers.yaml
        spack external find
        echo "::endgroup::"
