name: Test plugins

env:
  spack_version: v1.0.0-alpha.2
  esmf_version: develop
  compiler_version: latest
  install_dir: ${{ github.workspace }}/app

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  types: [opened, synchronize, reopened, labeled, unlabeled]
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Core Development Tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install tar unzip file gringo
        sudo apt-get -qq install build-essential binutils-dev gfortran
      shell: bash

    - name: Checkout Component Repository
      uses: actions/checkout@v3
      with:
        path: ${{ env.install_dir }}/geogate
        
    - name: Create Spack Environment and Install Dependencies
      run: |
        ${{ env.install_dir }}/geogate/.github/workflows/scripts/install_deps.sh 
      shell: bash
