name: Test Catalyst Plugin with EGL

env:
  backend: egl
  catalyst: 2.0.0
  conduit: 0.9.2
  compiler: gcc@14.2.0
  coupling: spmd
  esmf: 8.8.0
  paraview: 5.13.2
  spack: prereleases/v1.0.0-alpha.4

on:
  push:
    branches: [ feature/cicd ]

jobs:
  run-app:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Component Repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/app/geogate

    - name: Create Run Environment
      id: create-env
      uses: ./app/geogate/.github/actions/create_env
      with:
        backend: ${{ env.backend }}
        catalyst: ${{ env.catalyst }}
        conduit: ${{ env.conduit }}
        compiler: ${{ env.compiler }}
        esmf: ${{ env.esmf }}
        install_dir: ${{ github.workspace }}/app
        paraview: ${{ env.paraview }}
        spack: ${{ env.spack }}

    - name: Test
      run: |
        echo ${{ github.workspace }}
        echo ${{ steps.create-env.outputs.cache_name }}
        echo ${{ steps.create-env.outputs.pkgs_list }}
      shell: bash
